-- Multi-Tenant E-Commerce, Inventory, and POS Platform PostgreSQL Database Schema

-- Drop existing tables to start fresh
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS company_settings CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS subscription_plans CASCADE;

-- 1. Subscription Plans Table
CREATE TABLE subscription_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    billing_cycle VARCHAR(50) DEFAULT 'monthly' NOT NULL,
    features JSONB,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 2. Companies Table (Tenants)
CREATE TABLE companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    subdomain VARCHAR(100) UNIQUE NOT NULL,
    logo_url VARCHAR(500),
    banner_url VARCHAR(500),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    address TEXT,
    delivery_charge DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    subscription_plan_id INT REFERENCES subscription_plans(id) ON DELETE SET NULL,
    subscription_expires_at TIMESTAMP WITH TIME ZONE,
    approval_status VARCHAR(50) DEFAULT 'Pending' NOT NULL,
    owner_name VARCHAR(255),
    owner_mobile VARCHAR(50),
    company_mobile VARCHAR(50),
    facebook_link VARCHAR(500),
    instagram_link VARCHAR(500),
    bkash_number VARCHAR(50),
    nagad_number VARCHAR(50),
    bank_name VARCHAR(255),
    bank_account_name VARCHAR(255),
    division VARCHAR(100),
    district VARCHAR(100),
    thana VARCHAR(100),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 3. Roles Table (System roles)
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    value VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 4. Permissions Table
CREATE TABLE permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(255),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 5. Role-Permissions Join Table
CREATE TABLE role_permissions (
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INT REFERENCES permissions(id) ON DELETE CASCADE,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (role_id, permission_id)
);

-- 6. Users Table (Multi-Tenant)
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    user_type VARCHAR(50) DEFAULT 'CompanyUser' NOT NULL,
    address TEXT,
    otp VARCHAR(50),
    otp_expires_at TIMESTAMP WITH TIME ZONE,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 7. User-Roles Join Table
CREATE TABLE user_roles (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (user_id, role_id)
);

-- 8. Suppliers Table
CREATE TABLE suppliers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    phone_number VARCHAR(50),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 9. Categories Table (Tenant-isolated)
CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    parent_id INT REFERENCES categories(id) ON DELETE SET NULL,
    sizes VARCHAR(500),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    UNIQUE (company_id, slug)
);

-- 10. Brands Table (Tenant-isolated)
CREATE TABLE brands (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    logo_url VARCHAR(500),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    UNIQUE (company_id, slug)
);

-- 11. Products Table (Tenant-isolated)
CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    barcode VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    wholesale_price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT DEFAULT 0 NOT NULL,
    status VARCHAR(50) DEFAULT 'PUBLISHED' NOT NULL,
    image_url VARCHAR(500),
    category_id INT REFERENCES categories(id) ON DELETE SET NULL,
    brand_id INT REFERENCES brands(id) ON DELETE SET NULL,
    supplier_id INT REFERENCES suppliers(id) ON DELETE SET NULL,
    size VARCHAR(100),
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    UNIQUE (company_id, sku),
    UNIQUE (company_id, barcode)
);

-- 12. Orders Table (POS & E-commerce orders)
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    order_number VARCHAR(100) NOT NULL,
    sale_type VARCHAR(50) DEFAULT 'ECOMMERCE' NOT NULL,
    sales_staff_id INT REFERENCES users(id) ON DELETE SET NULL,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(50),
    status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    tax DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    shipping_fee DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    UNIQUE (company_id, order_number)
);

-- 13. Order Items Table
CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    product_id INT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 14. Payments Table
CREATE TABLE payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    order_id INT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    transaction_id VARCHAR(255),
    provider VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    payment_type VARCHAR(50) DEFAULT 'AUTOMATED' NOT NULL,
    sender_number VARCHAR(50),
    reference_log TEXT,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- 15. Company Settings Table
CREATE TABLE company_settings (
    company_id INT REFERENCES companies(id) ON DELETE CASCADE NOT NULL,
    key VARCHAR(100) NOT NULL,
    value TEXT NOT NULL,
    group_name VARCHAR(50) DEFAULT 'GENERAL' NOT NULL,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (company_id, key)
);

-- 16. Audit Logs Table
CREATE TABLE audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_by INT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by INT,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_by INT,
    deleted_date TIMESTAMP WITH TIME ZONE
);

-- Seed global subscriptions
INSERT INTO subscription_plans (name, price, billing_cycle, features) VALUES
('Basic Plan', 1500.00, 'monthly', '{"max_products": 200, "pos_enabled": true, "ecommerce_enabled": true}'),
('Premium Plan', 3500.00, 'monthly', '{"max_products": 5000, "pos_enabled": true, "ecommerce_enabled": true, "multi_staff": true}');

-- Seed system roles with names as lowercase strings, and display values
INSERT INTO roles (name, value, description) VALUES
('superadmin', 'Super Admin', 'Platform Owner - Full access to all system tenants, subscriptions, and diagnostics'),
('companyadmin', 'Company Admin', 'Company Owner - Full access to specific company settings, reports, staff management'),
('companymanager', 'Company Manager', 'Company Store Manager - Manage inventory, store config, and view basic reports'),
('salesstaff', 'Sales Staff', 'POS Checkout Operator - Restricted access to barcodes scanner, checkout register, and personal sales logs'),
('customer', 'Customer', 'End Customer');

-- Seed default permissions
INSERT INTO permissions (name, description) VALUES
('platform:diagnostics', 'Access to SaaS metrics and platform logs'),
('manage:companies', 'Add, suspend, or upgrade tenant companies'),
('manage:subscriptions', 'Configure billing plans and approve payment references'),
('company:settings', 'Update company-wide configuration and delivery charges'),
('manage:staff', 'Create, update, and deactivate managers and checkout staff'),
('manage:inventory', 'Create products, edit prices, trigger barcode generation'),
('pos:checkout', 'Scan barcodes and complete register checkout'),
('reports:full', 'Access full company financial and inventory audits'),
('reports:operational', 'Access inventory stock alerts and daily staff cashier sheets');

-- Map Super Admin Role Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'superadmin' AND p.name IN ('platform:diagnostics', 'manage:companies', 'manage:subscriptions');

-- Map Company Admin Role Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'companyadmin' AND p.name IN ('company:settings', 'manage:staff', 'manage:inventory', 'pos:checkout', 'reports:full');

-- Map Company Manager Role Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'companymanager' AND p.name IN ('manage:inventory', 'pos:checkout', 'reports:operational');

-- Map Sales Staff Role Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'salesstaff' AND p.name IN ('pos:checkout');
